
ALTER TABLE public.store_settings
  ADD COLUMN IF NOT EXISTS logo_url TEXT,
  ADD COLUMN IF NOT EXISTS tax_id TEXT,
  ADD COLUMN IF NOT EXISTS receipt_header TEXT,
  ADD COLUMN IF NOT EXISTS receipt_footer TEXT DEFAULT 'Thank you for shopping with us!',
  ADD COLUMN IF NOT EXISTS paper_width TEXT NOT NULL DEFAULT '80mm',
  ADD COLUMN IF NOT EXISTS show_logo BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_tax_id BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_address BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_phone BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_tax_lines BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_cashier BOOLEAN NOT NULL DEFAULT true;
