// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

// proxyUrl/directUrl let REST/Auth calls recover if the Cloudflare Worker
// proxy itself is the thing failing (rate-limited, out of quota, or down) —
// see the fallback logic below. Pass directUrl as undefined when there's no
// real Supabase URL configured to fall back to (nothing to do then).
function createSupabaseFetch(supabaseKey: string, proxyUrl: string, directUrl: string | undefined): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    const requestInit = { ...init, headers };

    // Fall back once, straight to the real Supabase URL, if the proxy itself
    // looks unhealthy (unreachable, or answering with a server error / rate
    // limit) rather than a genuine API error from Supabase. This only helps
    // shops whose ISP doesn't itself block supabase.co directly — for those
    // that do, the direct attempt will fail too and the app's existing
    // offline queue takes over, same as any other outage.
    const retryDirect = (url: string) => fetch(directUrl + url.slice(proxyUrl.length), requestInit);

    try {
      const res = await fetch(input, requestInit);
      if (!directUrl || (res.status < 500 && res.status !== 429)) return res;
      const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
      if (!url.startsWith(proxyUrl)) return res;
      const direct = await retryDirect(url);
      return direct.status < 500 ? direct : res;
    } catch (err) {
      if (!directUrl) throw err;
      const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : (input as Request).url;
      if (!url.startsWith(proxyUrl)) throw err;
      return retryDirect(url);
    }
  };
}


function createSupabaseClient() {
  // process.env.SUPABASE_* is populated by the Vercel Supabase integration
  // (kept current automatically when the connected project changes) and is
  // checked first; VITE_SUPABASE_* falls back for environments where that
  // integration isn't present (e.g. local dev, the Lovable sandbox).
  //
  // Some regions cannot reach supabase.co directly, so production browser
  // builds route through the public Cloudflare Worker proxy by default.
  // DIRECT_URL is also handed to createSupabaseFetch below so REST/Auth
  // calls can fall back to it if the proxy itself is ever the thing that's
  // broken (out of its own request quota, down, etc.) — see that function.
  const PROXY_URL = import.meta.env.VITE_SUPABASE_PROXY_URL ?? 'https://aged-truth-688d.shahidmehmoodai52.workers.dev';
  const DIRECT_URL = process.env.SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_URL = PROXY_URL || DIRECT_URL;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY, PROXY_URL, DIRECT_URL !== PROXY_URL ? DIRECT_URL : undefined),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      // The realtime websocket connects through the same PROXY_URL as every
      // other request above. When that proxy can't establish the connection
      // (e.g. it doesn't forward the WebSocket Upgrade handshake), the
      // client's default backoff caps out at a 10s retry forever — which
      // across a handful of open tabs adds up to ~1000 failed connection
      // attempts/hour, 24/7, even overnight with nobody using the app. Ramp
      // the backoff up to a 5-minute ceiling instead so a broken connection
      // stops hammering the proxy while still recovering once it's fixed.
      reconnectAfterMs: (tries: number) => Math.min(1000 * 2 ** tries, 300_000),
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

